home/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index),
    path('doanvien/', views.doanvien, name= 'doanvien'),
    path('doankhoa/', views.doankhoa, name='doankhoa'),
    path('doankhoa/add/', views.add_doankhoa, name='add_doankhoa'),
    path('doankhoa/<str:maDK>/delete/', views.delete_doankhoa, name='delete_doankhoa'),
    path('doankhoa/edit/<str:maDK>/', views.edit_doankhoa, name='edit_doankhoa'),
    path('doankhoa/export/', views.export_doankhoa, name='export_doankhoa'),
    path('doankhoa/import/', views.import_doankhoa, name='import_doankhoa'),
    path('chidoan/', views.chidoan, name='chidoan'),
    path('chidoan/add/', views.add_chidoan, name='add_chidoan'),
    # name='add_chidoan nay coi nhu la 1 bien dai dien cho url de có thể sử dụng trong html
    path('chidoan/<str:maCD>/delete/', views.delete_chidoan, name='delete_chidoan'),
    path('chidoan/edit/<str:maCD>/', views.edit_chidoan, name='edit_chidoan'),
    path('chidoan/export/', views.export_chidoan, name='export_chidoan'),
    path('chidoan/import/', views.import_chidoan, name='import_chidoan'),
    path('doanvien/', views.doanvien, name='doanvien'),
    path('doanvien/add/', views.add_doanvien, name='add_doanvien'),
    path('doanvien/<str:maDV>/delete/', views.delete_doanvien, name='delete_doanvien'),
    path('doanvien/edit/<str:maDV>/', views.edit_doanvien, name='edit_doanvien'),
    # name='add_doanvien nay coi nhu la 1 bien dai dien cho url de có thể sử dụng trong html
    path('doanvien/import/', views.import_doanvien, name='import_doanvien'),
    path('doanvien/export/', views.export_doanvien, name='export_doanvien'),

    path('hocky/add/', views.add_hocky, name='add_hocky'),
    path('doanphi/', views.doanphi, name='doanphi'),
    path('doanphi/add/', views.add_doanphi, name='add_doanphi'),
    path('doanphi/edit/<str:maDP>', views.edit_doanphi, name='edit_doanphi'),
]

quanlydoanvien/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

home/models.py
from django.db import models

# Create your models here.
class Doankhoa(models.Model):
    maDK = models.CharField(max_length= 10, primary_key= True)
    tenDK = models.CharField(max_length=255, null=False)
    def __str__(self):
        return f'{self.maDK}'
    
    class Meta:
        db_table = 'doankhoa'
        verbose_name = 'Đoàn Khoa'
        verbose_name_plural = 'Các Đoàn Khoa'
        
class Chidoan(models.Model):
    maCD = models.CharField(max_length=50, primary_key=True)
    tenCD = models.CharField(max_length=255, null=False)
    maDK = models.ForeignKey(Doankhoa, on_delete=models.CASCADE)

    def __str__(self):
        return self.tenCD

    class Meta:
        db_table = 'chidoan'
        verbose_name = 'Chi Đoàn'
        verbose_name_plural = 'Các Chi Đoàn'

class Chucvu(models.Model):
    maCV = models.CharField(max_length=20, primary_key=True)
    tenCV = models.CharField(max_length=100)

    def __str__(self):
        return self.tenCV
    class Meta:
            db_table = 'chucvu'
            verbose_name = 'Chức Vụ'
            verbose_name_plural = 'Các Chức Vụ'

class Doanvien(models.Model):
    maDV = models.CharField(max_length=20, primary_key=True)  # Mã Đoàn Viên
    tenDV = models.CharField(max_length=100)  # Tên Đoàn Viên
    maCD = models.ForeignKey(Chidoan, on_delete=models.CASCADE)  # Liên kết đến Chi Đoàn
    GIOI_TINH_CHOICES = [
        (0, 'Nam'),
        (1, 'Nữ'),
    ]
    gioi_tinh = models.PositiveSmallIntegerField(choices=GIOI_TINH_CHOICES, default=0)
    ngay_sinh = models.DateField()  # Ngày Sinh
    que_quan = models.CharField(max_length=100)  # Quê Quán
    sdt = models.CharField(max_length=15, default='N/A')  # Cung cấp giá trị mặc định
    ngay_vao_doan = models.DateField()  # Ngày Vào Đoàn
    maCV = models.ForeignKey(Chucvu, on_delete=models.CASCADE, default = "Đoàn viên")  # Liên kết đến Chức Vụ

    def __str__(self):
        return self.tenDV
    class Meta:
        db_table = 'doanvien'
        verbose_name = 'Đoàn Viên'
        verbose_name_plural = 'Các Đoàn Viên' 

class Hocky(models.Model):
    maHK = models.CharField(max_length=10, primary_key=True)  # Mã học kỳ
    tenHK = models.CharField(max_length=100)  # Tên học kỳ (ví dụ: "Học Kỳ 1 Năm 2024")

    def __str__(self):
        return self.tenHK

    class Meta:
        db_table = 'hocky'
        verbose_name = 'Học Kỳ'
        verbose_name_plural = 'Các Học Kỳ'

class Doanphi(models.Model):
    TRANGTHAI_CHOICES = [
        (0, 'Chưa đóng'),
        (1, 'Đã đóng'),
    ]

    maDP = models.CharField(max_length=20, primary_key=True)
    maDV = models.ForeignKey(Doanvien, on_delete=models.CASCADE)
    sotien = models.DecimalField(max_digits=10, decimal_places=2)
    hocky = models.ForeignKey(Hocky, on_delete=models.CASCADE)
    trangthai = models.PositiveSmallIntegerField(choices=TRANGTHAI_CHOICES, default=0)
    
    def __str__(self):
        return f'{self.maDV} - {self.sotien} VNĐ - {self.hocky}'

    class Meta:
        db_table = 'doanphi'
        verbose_name = 'Đoàn Phí'
        verbose_name_plural = 'Các Đoàn Phí'

home/views.py
from django.db import transaction
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
#  Sử dụng Q objects từ Django để kết hợp nhiều điều kiện tìm kiếm.
from django.db.models import Q
from .models import Doankhoa, Chidoan, Doanvien, Chucvu, Doanphi, Hocky
from .forms import DoankhoaForm, ChidoanForm, DoanvienForm, DoanphiForm, DoanphiFilterForm, ThemDoanphiForm, ThemHockyForm
# goi thu vien pandas xay dung chuc nang import/export 
import pandas
import openpyxl
from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows
from openpyxl.styles import Border, Side, Alignment
from .forms import ImportExcelForm 
from datetime import datetime
# Create your views here.
def index(request):
    return render(request, 'pages/home.html')
def doankhoa(request):
    # Lấy thông tin từ query tìm kiếm
    query = request.GET.get('search')
    # Kiểm tra nếu có query, thì lọc theo tên khoa
    if query:
        #  Sử dụng Q objects từ Django để kết hợp nhiều điều kiện tìm kiếm.
        doan_khoas = Doankhoa.objects.filter(Q(tenDK__icontains=query) | Q(maDK__icontains=query))
    else:
        doan_khoas = Doankhoa.objects.all()

    # Trả về trang doankhoa với danh sách doankhoa đã lọc
    return render(request, 'pages/doankhoa.html', {'doan_khoas': doan_khoas})
def add_doankhoa(request):
    if request.method == 'POST':
        form = DoankhoaForm(request.POST)
        if form.is_valid():
            form.save()  # Lưu vào database
            # thông báo 
            messages.success(request, 'Thêm thành công!')
            return redirect('doankhoa')  # Chuyển hướng về trang danh sách Đoàn Khoa
        else:
            messages.error(request, 'Thêm thất bại, vui lòng kiểm tra lại thông tin, có thể thông tin đã tồn tại.')
            return redirect('add_doankhoa')
    else:
        form = DoankhoaForm()
    return render(request, 'pages/add_doankhoa.html', {'form': form})
# Phan chinh sua doan khoa
def edit_doankhoa(request, maDK):
    # Lấy đối tượng Đoàn Khoa theo maDK
    doan_khoa = Doankhoa.objects.get(maDK=maDK)
    # Kiểm tra nếu phương thức là POST để cập nhật thông tin
    if request.method == 'POST':
        form = DoankhoaForm(request.POST, instance=doan_khoa)  # Dùng instance để cập nhật
        if form.is_valid():
            form.save()
            messages.success(request, 'Thông tin Đoàn Khoa đã được cập nhật thành công.')
            return redirect('doankhoa')  # Chuyển hướng về trang danh sách Đoàn Khoa sau khi sửa
    else:
        form = DoankhoaForm(instance=doan_khoa)  # Hiển thị form với dữ liệu của Đoàn Khoa cần sửa

    # Render template với form và đối tượng
    return render(request, 'pages/edit_doankhoa.html', {'form': form})
# Phan xoa Doan Khoa
def delete_doankhoa(request, maDK):
    doan_khoa = Doankhoa.objects.get(maDK=maDK)
    if request.method == 'POST':
        doan_khoa.delete()
        messages.success(request, 'Xóa thành công Đoàn Khoa!')
        return redirect('doankhoa')
    return render(request, 'pages/doankhoa.html', {'object': doan_khoa})
# Chuc nang export DoanKhoa
def export_doankhoa(request):
    # Lấy dữ liệu từ model Doankhoa
    doan_khoas = Doankhoa.objects.all().values('maDK', 'tenDK')

    if not doan_khoas.exists():
        messages.error(request, "Không có dữ liệu để xuất ra file Excel.")
        return redirect('doankhoa')  # Quay lại trang danh sách

    # Tạo workbook và sheet
    wb = Workbook()
    ws = wb.active
    ws.title = "Danh sách Đoàn Khoa"

    # Tiêu đề cột
    headers = ['STT', 'Mã Khoa', 'Tên Khoa']

    # Kẻ khung cho ô
    thin_border = Border(left=Side(style='thin'),
                         right=Side(style='thin'),
                         top=Side(style='thin'),
                         bottom=Side(style='thin'))

    # Thêm tiêu đề vào sheet
    for col_num, header in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col_num, value=header)
        cell.alignment = Alignment(horizontal='center')  # Căn giữa tiêu đề
        cell.border = thin_border  # Kẻ khung cho tiêu đề

    # Thêm dữ liệu vào sheet và điều chỉnh chiều rộng cột
    for row_num, doan_khoa in enumerate(doan_khoas, 2):  # Bắt đầu từ hàng thứ 2
        # Cột STT
        cell_stt = ws.cell(row=row_num, column=1, value=row_num - 1)
        cell_stt.alignment = Alignment(horizontal='center')  # Căn giữa cột số thứ tự
        cell_stt.border = thin_border  # Kẻ khung cho cột STT

        # Cột Mã Khoa
        cell_ma_khoa = ws.cell(row=row_num, column=2, value=doan_khoa['maDK'])
        cell_ma_khoa.border = thin_border  # Kẻ khung cho cột Mã Khoa

        # Cột Tên Khoa
        cell_ten_khoa = ws.cell(row=row_num, column=3, value=doan_khoa['tenDK'])
        cell_ten_khoa.border = thin_border  # Kẻ khung cho cột Tên Khoa

        # Điều chỉnh chiều rộng của cột STT (giảm kích thước)
        ws.column_dimensions['A'].width = 5  # Chiều rộng cụ thể cho cột STT
        # Điều chỉnh chiều rộng cho cột Mã Khoa và Tên Khoa
        ws.column_dimensions['B'].width = max(ws.column_dimensions['B'].width, len(str(doan_khoa['maDK'])) + 2)  # Cột Mã Khoa
        ws.column_dimensions['C'].width = max(ws.column_dimensions['C'].width, len(str(doan_khoa['tenDK'])) + 2)  # Cột Tên Khoa

    # Kẻ khung cho tất cả các ô trong bảng
    for row in ws.iter_rows(min_row=1, min_col=1, max_row=len(doan_khoas) + 1, max_col=len(headers)):
        for cell in row:
            cell.border = thin_border

    # Tạo response với file excel
    response = HttpResponse(content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = 'attachment; filename="doankhoa.xlsx"'

    # Xuất file Excel
    wb.save(response)
    return response
# chuc nang import DoanKhoa
def import_doankhoa(request):
    if request.method == 'POST':
        form = ImportExcelForm(request.POST, request.FILES)
        if form.is_valid():
            excel_file = request.FILES['file']  # Nhận file từ form

            # Đọc file Excel bằng pandas
            try:
                df = pandas.read_excel(excel_file)

                # Kiểm tra xem file có đúng cấu trúc hay không
                if not all(col in df.columns for col in ['STT', 'Mã Khoa', 'Tên Khoa']):
                    messages.error(request, "File không đúng định dạng. Vui lòng kiểm tra lại.")
                    return redirect('import_doankhoa')

                # Lặp qua các dòng và lưu vào model Doankhoa
                for _, row in df.iterrows():
                    Doankhoa.objects.update_or_create(
                        maDK=row['Mã Khoa'],  # Xác định dựa trên Mã Khoa
                        defaults={'tenDK': row['Tên Khoa']}  # Cập nhật tên khoa
                    )
                messages.success(request, 'Import dữ liệu thành công!')
                return redirect('doankhoa')  # Chuyển hướng về trang danh sách
            except Exception as e:
                messages.error(request, f"Có lỗi xảy ra: {str(e)}")
                return redirect('import_doankhoa')
    else:
        form = ImportExcelForm()

    return render(request, 'pages/import_doankhoa.html', {'form': form})

def chidoan(request):
    query = request.GET.get('search')
    if query:
        chidoans = Chidoan.objects.filter(Q(tenCD__icontains=query) | Q(maCD__icontains=query))
    else:
        chidoans = Chidoan.objects.all()

    return render(request, 'pages/chidoan.html', {'chidoans': chidoans})

def add_chidoan(request):
    if request.method == 'POST':
        form = ChidoanForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Thêm thành công!')
            return redirect('chidoan')
        else:
            messages.error(request, 'Thêm thất bại, vui lòng kiểm tra lại thông tin, có thể thông tin đã tồn tại.')
            return redirect('add_chidoan')
    else:
        form = ChidoanForm()
        doankhoas = Doankhoa.objects.all()  # Lấy tất cả các Đoàn Khoa
    return render(request, 'pages/add_chidoan.html', {'form': form, 'doankhoas': doankhoas})

def edit_chidoan(request, maCD):
    chi_doan = Chidoan.objects.get(maCD=maCD)
    # Kiểm tra nếu phương thức là POST để cập nhật thông tin
    if request.method == 'POST':
        form = ChidoanForm(request.POST, instance=chi_doan)  # Dùng instance để cập nhật
        if form.is_valid():
            form.save()
            messages.success(request, 'Thông tin Chi Đoàn đã được cập nhật thành công.')
            return redirect('chidoan')
    else:
        form = ChidoanForm(instance=chi_doan)

    return render(request, 'pages/edit_chidoan.html', {'form': form})

def delete_chidoan(request, maCD):
    chi_doan = Chidoan.objects.get(maCD=maCD)
    if request.method == 'POST':
        chi_doan.delete()
        messages.success(request, 'Xóa thành công Chi Đoàn!')
        return redirect('chidoan')
    return render(request, 'pages/delete_chidoan.html', {'object': chi_doan})
def export_chidoan(request):
    chidoans = Chidoan.objects.all().values('maCD', 'tenCD', 'maDK')

    if not chidoans.exists():
        messages.error(request, "Không có dữ liệu để xuất ra file Excel.")
        return redirect('chidoan')

    wb = Workbook()
    ws = wb.active
    ws.title = "Danh sách Chi Đoàn"

    headers = ['STT', 'Mã Chi Đoàn', 'Tên Chi Đoàn', 'Đoàn Khoa']

    thin_border = Border(left=Side(style='thin'),
                         right=Side(style='thin'),
                         top=Side(style='thin'),
                         bottom=Side(style='thin'))

    for col_num, header in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col_num, value=header)
        cell.alignment = Alignment(horizontal='center')
        cell.border = thin_border

    for row_num, chidoan in enumerate(chidoans, 2):
        cell_stt = ws.cell(row=row_num, column=1, value=row_num - 1)
        cell_stt.alignment = Alignment(horizontal='center')
        cell_stt.border = thin_border

home/templates/pages/add_chidoan.html
{% extends "pages/base.html" %}

{% block title %}Thêm Chi Đoàn{% endblock  %}

{% block content %}
    <h2 style="padding: 20px;">THÊM CHI ĐOÀN</h2>
    {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                        {{ message }}
                    </li>
                {% endfor %}
            </ul>
    {% endif %}
    <form class="add-chidoan-form" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <!-- Nút thêm -->
        <div class="button-edit-add-form">
            <div>
                <button type="submit" class="btn btn-success">Thêm</button>
            </div>
            <div>
                {% comment %} thêm nút hủy cho quay lại trang {% endcomment %}
                <a href="/chidoan"><button type="button" class="btn btn-cancel">Hủy</button></a>
            </div>
        </div>
    </form>
{% endblock  %}

home/templates/pages/add_doankhoa.html
{% extends "pages/base.html" %}

{% block title %}Thêm Đoàn Khoa{% endblock  %}

{% block content %}
    <h2 style="padding: 20px;">THÊM ĐOÀN KHOA</h2>
    {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                        {{ message }}
                    </li>
                {% endfor %}
            </ul>
    {% endif %}
    <form class="add-doankhoa-form" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <!-- Nút thêm -->
        <div class="button-edit-add-form">
            <div>
                <button type="submit" class="btn btn-success">Thêm</button>
            </div>
            <div>
                {% comment %} thêm nút hủy cho quay lại trang {% endcomment %}
                <a href="/doankhoa"><button type="button" class="btn btn-cancel">Hủy</button></a>
            </div>
        </div>
    </form>
{% endblock  %}

home/templates/pages/add_doanvien.html
{% extends "pages/base.html" %}

{% block title %}Thêm Đoàn Khoa{% endblock  %}

{% block content %}
    <h2 style="padding:20px 30px;">THÊM ĐOÀN VIÊN</h2>
    {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                        {{ message }}
                    </li>
                {% endfor %}
            </ul>
    {% endif %}
    <div class="conten-doanvien">
        <form class="add-doanvien-forms" method="POST">
            {% csrf_token %}
            <p>
                <label for="id_maDV">Mã Đoàn Viên:</label>
                <input type="text" name="maDV" placeholder="Mã Đoàn Viên" maxlength="20" required id="id_maDV">
            </p>
    
            <p>
                <label for="id_tenDV">Tên Đoàn Viên:</label>
                <input type="text" name="tenDV" placeholder="Tên Đoàn Viên" maxlength="100" required id="id_tenDV">
            </p>
    
            <p>
                <label for="id_maCD">Mã Chi Đoàn:</label>
                <input type="text" name="maCD" placeholder="Mã Chi Đoàn" required id="id_maCD">
            </p>
    
           
    
            <p>
                <label for="id_ngay_sinh">Ngày Sinh:</label>
                <input type="date" name="ngay_sinh" placeholder="Ngày Sinh" required id="id_ngay_sinh">
            </p>
    
            <p>
                <label for="id_que_quan">Quê Quán:</label>
                <input type="text" name="que_quan" placeholder="Quê Quán" maxlength="100" required id="id_que_quan">
            </p>
    
            <p>
                <label for="id_sdt">SĐT:</label>
                <input type="text" name="sdt" value="N/A" placeholder="SĐT" maxlength="15" required id="id_sdt">
            </p>
    
            <p>
                <label for="id_ngay_vao_doan">Ngày Vào Đoàn:</label>
                <input type="date" name="ngay_vao_doan" placeholder="Ngày Vào Đoàn" required id="id_ngay_vao_doan">
            </p>
    
            <p class="option">
                <label for="id_maCV">Chức Vụ:</label>
                <select name="maCV" class="form-controls" required id="id_maCV">
                    <option value="" selected>---------</option>
                    {% for chucvu in chucvus %}
                        <option value="{{ chucvu.maCV }}">{{ chucvu.tenCV }}</option>
                    {% endfor %}
                </select>
            </p>
            <p class ="option">
                <label for="id_gioi_tinh">Giới Tính:</label>
                <select name="gioi_tinh" class="form-controls" id="id_gioi_tinh">
                <option value="0" selected>Nam</option>
                <option value="1">Nữ</option>
                </select>
            </p>
            <!-- Nút thêm -->
            <div class="button-edit-add-forms">
                <div>
                    <button type="submit" class="btns btn-successs">Thêm</button>
                    <a href="/doanvien"><button type="button" class="btns btn-cancels">Hủy</button></a>
                </div>
            </div>
        </form>
    </div>
{% endblock  %}

home/templates/pages/add_hocky.html
{% extends "pages/base.html" %}

{% block title %}Thêm Học Kỳ{% endblock  %}

{% block content %}
    <h2 style="padding: 20px;">THÊM HỌC KỲ</h2>
    {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                        {{ message }}
                    </li>
                {% endfor %}
            </ul>
    {% endif %}
    <form class="add-hocky-form" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <!-- Nút thêm -->
        <div class="button-edit-add-form">
            <div>
                <button type="submit" class="btn btn-success">Thêm</button>
            </div>
            <div>
                {% comment %} thêm nút hủy cho quay lại trang {% endcomment %}
                <a href="/doanphi"><button type="button" class="btn btn-cancel">Hủy</button></a>
            </div>
        </div>
    </form>
{% endblock  %}

home/templates/pages/doanvien.html
{% extends "pages/base.html" %}

{% block title %}Chi Đoàn{% endblock  %}

{% block content %}
    <h1 class="list-header-name">DANH SÁCH ĐOÀN VIÊN</h1>
    {% comment %} chuc nang them {% endcomment %}
    <a class="button-add" href="{% url 'add_doanvien' %}">
        <button><i class="ti-plus"></i> Thêm mới</button>
    </a>
    {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                        {{ message }}
                    </li>
                {% endfor %}
            </ul>
    {% endif %}

    {% comment %} ----------------------------------------------------- {% endcomment %}
    <br>
    <br>
    {% comment %} tao khung gid cho 2 chuc nang tim kiem va nhap xuat file excel {% endcomment %}
    <div class="gid-form-search-im-ex">
    {% comment %} chuc nang tim kiem {% endcomment %}
        <div>
            <h4 style="padding: 0px 20px;">Tìm Kiếm theo: Mã-Tên đoàn viên hoặc mã Chi đoàn: </h4>
            <div class="search-container">
                <form method="GET" action="{% url 'doanvien' %}">
                    <input class="thanh-tim-kiem" type="text" name="search" placeholder="Nhập từ khóa để tìm kiếm...">
                    {% comment %}  name="search" xem nhu la bien dai dien cho data cua thk input de dua vao view su li {% endcomment %}
                    <button class="search-button" type="submit">Tìm kiếm</button>
                </form>
            </div>
        </div>
    {% comment %} ----------------------------------------------------- {% endcomment %}
    {% comment %} chức năng import và export {% endcomment %}
        <div class="ex-im-comtainer">
            <p style="padding: 5px 7px;">Nhập/Xuất file excel: </p>
            <a href="{% url 'export_doanvien' %}" class="ti-export"></a>
            <a href="{% url 'import_doanvien' %}" class="ti-import"></a>
        </div>
    {% comment %} ----------------------------------------------------- {% endcomment %}
    </div>
    <br>
    {% comment %} Hien thi thong tin bảng doan khoa {% endcomment %}
    <div class="table-container">
        <table>
            <thead>
                <tr>
                    <th width="5%">STT</th>                
                    <th width="10%">Mã Đoàn Viên</th>       
                    <th width="15%">Tên Đoàn Viên</th>      
                    <th width="10%">Mã Chi Đoàn</th>       
                    <th width="8%">Giới Tính</th>         
                    <th width="10%">Ngày Sinh</th>         
                    <th width="8%">Quê Quán</th>          
                    <th width="10%">Số điện thoại</th>      
                    <th width="8%">Ngày Vào Đoàn</th>     
                    <th width="10%">Chuc vu</th>  
                    <th width="15%">Hành Động</th>         
                    
                </tr>
            </thead>
            <tbody>
                {% for doanvien in doanviens %}
                <tr>
                    {% comment %} forloop dùng để đánh số thứ tự {% endcomment %}
                    <td>{{ forloop.counter }}</td>
                    <td>{{ doanvien.maDV }}</td>
                    <td>{{ doanvien.tenDV }}</td>
                    <td>{{ doanvien.maCD.maCD }}</td> <!-- Reference to Chi Đoàn -->
                    <td>{{ doanvien.get_gioi_tinh_display }}</td> <!-- For choice fields -->
                    <td>{{ doanvien.ngay_sinh|date:"d/m/Y" }}</td>
                    <td>{{ doanvien.que_quan }}</td>
                    <td>{{ doanvien.sdt }}</td>
                    <td>{{ doanvien.ngay_vao_doan|date:"d/m/Y" }}</td>
                    <td>{{ doanvien.maCV }}</td>
                    <td>
                        <div style="display: grid; grid-template-columns: auto auto;">
                            <div>
                               <!-- Nút Sửa Dang test-->
                               <a href="{% url 'edit_doanvien' doanvien.maDV %}">
                                <button class="btn btn-primary"><p class="ti-write"></p></button>
                                </a> 
                            </div>
                            <div>
                                 <!-- Nút Xóa -->
                                <button class="btn btn-danger" onclick="confirmDeletedDoanVien('{{ doanvien.maDV }}')">
                                    <p class="ti-trash"></p>
                                </button>
                            </div>
                            
                        </div>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="11">Không có dữ liệu.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% comment %} ----------------------------------------------------- {% endcomment %}
    {% comment %} Modal xác nhận xóa chi đoàn {% endcomment %}
    <div id="confirmDeleteModalDoanVien" class="modal">
        <div class="confirm-box">
            <h3>Bạn có chắc chắn muốn xóa Đoàn Viên không?</h3>
            <p>Hành động này sẽ không thể hoàn tác.</p>
            <form method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger" >Xác nhận</button>
                <button type="button" class="btn btn-cancel" onclick="closeModalDoanVien()">Hủy</button>

            </form>
        </div>
    </div>
    
    {% comment %} ----------------------------------------------------- {% endcomment %}
{% endblock  %}

home/templates/pages/home.html
{% extends "pages/base.html" %}

{% block title %}Quản lý đoàn viên{% endblock  %}

{% block content %}
    <h1>Chào mừng bạn đã đến với hệ thống quản lý đoàn viên</h1>
{% endblock  %}